# Generated by Django 5.2.7 on 2025-10-11 03:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_name', models.CharField(max_length=10)),
                ('protein_feed', models.FloatField()),
                ('silage', models.FloatField()),
                ('minerals', models.FloatField()),
                ('milk_yield', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('is_ai_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cow')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('cow', 'date')},
            },
        ),
    ]
