# Generated by Django 5.2.7 on 2025-10-11 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dailyfeedrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfeedrecord',
            name='week_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
