# Generated by Django 5.2.7 on 2025-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dailyfeedrecord_week_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='health_condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('sick', 'Sick')], default='good', max_length=20),
        ),
    ]
